const Client = require('../')
let client = new Client()
client.listTradingPairs()
.then(console.log, console.error)
.then(() => client.listOrderbookPrecisions('BTC-USDT'))
.then(console.log, console.error)
.then(() => console.log('----------------cached------------'))
.then(() => client.listOrderbookPrecisions('BTC-USDT'))
.then(console.log, console.error)
.then(() => client.listFundingbookPrecisions('BTC'))
.then(console.log, console.error)
